version: '3.9'
services:
    apache:
        image: httpd:latest
        container_name: web-flashcards
        ports:
            - 4000:80
        volumes:
            - ./dist:/usr/local/apache2/htdocs
