name: CI/CD deployment & docs workflow

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v7

      - name: Set up conda environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: pfeil-dev
          init-shell: bash
          condarc: |
            channel_priority: strict
            channels:
                - conda-forge

      - name: Install dependencies
        run: |
          conda install -y --file dev-spec.txt
          npm install --save @types/jest
          npm install nunjucks

      - name: Build and commit documentation
        run: |
          # Configure git using GitHub Actions credentials.
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          make build
          git add -f dist
          git commit -m "Update documentation" dist || true

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: deploy-dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

